// Code generated by picgen. DO NOT EDIT.
package params

import (
	"math/big"

	"github.com/autonity/autonity/common"
)

var PiccadillyATNallocs = []struct {
	Address common.Address
	Value   *big.Int
}{
	{Address: common.HexToAddress("0x05C2ee5d563E75E431649CaECE1a598f862e5B02"), Value: mustParseString("100000000000000000000")},
	{Address: common.HexToAddress("0x0804A922ba6B7c0965928a8d9A10ecdeA0b3c41A"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x0916e717fcDBD625A99DfA468142D3EB251f6b5A"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x0aB543903ff68F1CdF948D3bDEf0706C14eAaB9B"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x100E38f7BCEc53937BDd79ADE46F34362470577B"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x11985c0b0C2df87f83Ba84b9a95C7C13e81c3a36"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x141AE1933A38D329A03cee280375815A5dE8e93b"), Value: mustParseString("115500000000000000000")},
	{Address: common.HexToAddress("0x197B2c44b887c4aC01243BDE7E4bBa8bd95BC3a8"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x1A9295c64508490B81285E7EAf64b6788383D8CC"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x1Be7f70BCf8393a7e4A5BcC66F6f15d6e35cfBBC"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x1cb9651394794b8F9948590973D591c262929AE6"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x1ef06a40f656feac2fd936adf1da3bea61040589"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x1f4b17C565e88d152e06A3938ca5830f7FFe6107"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x21ba84e40d5d3ae610078d287e336547570aa3fa"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x25B456f817B645B8f8Fd9d2A5C499B279aA12a2f"), Value: mustParseString("35000000000000000000")},
	{Address: common.HexToAddress("0x283c747f683375D80cA3050a37b1B14f6d243d07"), Value: mustParseString("115500000000000000000")},
	{Address: common.HexToAddress("0x2F8cEa90D5d8Eff154fe85841C771Ac33bB6EEb1"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x345de4128c57d4c9977e958ef5cbaf133d3041f6"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x3597d2D42f8Fbbc82E8b1046048773aD6DDB717E"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x36142A4f36974e2935192A1111C39330aA296D3C"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x23b4Be9536F93b8D550214912fD0e38417Ff7209"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x383A3c437d3F12f60E5fC990119468D3561EfBfc"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x3F3FeE9C908c43138d7e892CE33cAF85BDEc83e6"), Value: mustParseString("35000000000000000000")},
	{Address: common.HexToAddress("0x3d805a3f9efd6f5183aceddd7d531a9c37cb43cc"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x3fe573552E14a0FC11Da25E43Fef11e16a785068"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x42B683087647378Ea10323e415dCA76604D56d34"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x469C4A81d86461d1E85be1741b1a3152e5BB9b98"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x4c879c150463bb14c8B2e2307649E5Cd6BB4BDcE"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x526508c671eBD5311ebc3967Ac3F1D445907cC67"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x527192F3D2408C84087607b7feE1d0f907821E17"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x52a7c9895545c6e6b221af7a2ac708f0eefa09fd"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x551f3300FCFE0e392178b3542c009948008B2a9F"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x58F39270B5469b94914b96231da30D3DFB9cfEa8"), Value: mustParseString("35000000000000000000")},
	{Address: common.HexToAddress("0x5E17e837DcBa2728C94f95c38fA8a47CB9C8818F"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x5b9C621E304ef826eb94f554f85447F1e358Cb66"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x618CfCF7f73230552BE701fc1eBd835fA17e2d26"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x6636f811F6bfF4e2ce43A9a5009ae669eB8d9c5f"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x6747c02DE7eb2099265e55715Ba2E03e8563D051"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x6A4ece3e7c830c5115d8321aE1c29B90a69C7855"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x6B5b2750A59ff6Fc7B087d21454761e4C33E218B"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x6c5AE53a803796D788E917D1fE919BfC8B56d2E6"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x6d49071fb4D3eC08b99e89Bb06208B5FA8cF7907"), Value: mustParseString("35000000000000000000")},
	{Address: common.HexToAddress("0x718361fc3637199F24a2437331677D6B89a40519"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x725fC5416BDb173642D21DfC401519B0DCBf7f3b"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x75474aC55768fAb6fE092191eea8016b955072F5"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x842E176AF41eC98e3269FB752a17840d0589a2e5"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x8B458386eac12f4E16d23e74b3c19AF0B04812bB"), Value: mustParseString("1500000000000000000")},
	{Address: common.HexToAddress("0x8b914020A7099E4723f45561E897fa2740885A55"), Value: mustParseString("100000000000000000000")},
	{Address: common.HexToAddress("0x8f2c0eB1Ac36E74196E2cF8aBe3aF346105d1B0a"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x8f91e0ADF8065C3fFF92297267E02DF32C2978FF"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x9058AfE8910fAD6941B0D743F4db5A8EE987638F"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x94470A842Ea4f44e668EB9C2AB81367b6Ce01772"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x94CdeEfB31Dd0d430A3430e0680569714B115d4F"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x94d28f08Ff81A80f4716C0a8EfC6CAC2Ec74d09E"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x96841a9441ded4eb282e196b5a9b824d870c97e3"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x9691e63e8e90deCa91600502b6E040aDeD3d6503"), Value: mustParseString("1500000000000000000")},
	{Address: common.HexToAddress("0x99E2B4B27BDe92b42D04B6CF302cF564D2C13b74"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x9Af67224C16C6cAb7ef22A239329532325223A7c"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x9C7dAABb5101623340C925CFD6fF74088ff5672e"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x9C93Fe8e41137c4a23D8e525E2fa1b71e25b9252"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x9Cf765e8D8D3355956Dd7EE757bda5244A944a20"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0x9d28e40e9ec4789f9a0d17e421f76d8d0868ea44"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xA284470fa70D8A2A8402054e40A36077fEAdCF51"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xA8568B1f1E927E4d1AA4c0D248A3a9FFDD33A0dE"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xBBf36374eb23968F25aecAEbb97BF3118f3c2fEC"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xBE287C82A786218E008FF97320b08244BE4A282c"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xC0C483D9ABf549B73a2b6CfcFB2228321D15B25c"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xC2e1FBc007aE179c2EE9ED60E3CCe7087c35C749"), Value: mustParseString("115500000000000000000")},
	{Address: common.HexToAddress("0xC3B81e3f879C082a96Cad0cF0855F91847a64B31"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xC686DD5e936Be7a2491DC66689dba7ebe6A049eF"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xC9C7d1fA7adFb2856bB2F77f9F80fEa5F5a5073d"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xD6ed4dC54E1AA7A1cF5a925afAdb177133600566"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xDCA5DFF3D42f2db3C18dBE823380A0A81db49A7E"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xE052e6B778C2b9591548217C3372897513175684"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xE4686A4C6E63A8ab51B458c52EB779AEcf0B74f7"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xEf0Ba5e345C2C3937df5667A870Aae5105CAa3a5"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xFf02373228e1133Da0a16340350532b813f463Dc"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xa32a0cad4A19AF125dB862C28382c8C83939747c"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xa7705415B06e76075982C7e8BaCa4aAF3D6d0f28"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xaDF6a07D1f9D52bd9a464C8e3B1B670FD4b2cC55"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xaeD49e2A958F08338079294B2bC1E512eeB87914"), Value: mustParseString("100000000000000000000")},
	{Address: common.HexToAddress("0xb3fDCffE7863b5a450eB68E6dfda8Bc0f97EDb66"), Value: mustParseString("35000000000000000000")},
	{Address: common.HexToAddress("0xb41Ef07Ae29c45b9d7daB1a4608B1157E5D97B01"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xb5678C419aB603cFdf2a33589Bb7E5B73c7d2dC6"), Value: mustParseString("35000000000000000000")},
	{Address: common.HexToAddress("0xb7d8925BA077E89C1227Aa985de25d4ccC52F892"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xc175508b966bd5294d1d9bb2ffeec96b68945817"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xc1cbD63f219F39b41340ea3Dac320c22894bcC2e"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xc7dD8483e3dFAE05D0D86302382cc98E7F2706f0"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xc87d6957b5E7d3B268282630042037Bd873eC652"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xc8A6e810C8Ae52b7937C7b5756B80328172c022E"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xc945bC0C9A803864008e0A738Ed4e2CC523aE0D3"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xcdEed21b471b0Dc54faF74480A0E700fCc42a7b6"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xcf716b3930d7cf6f2ADAD90A27c39fDc9D643BBd"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xd22dE8e1720E1e6eb8Cb846259848e0627Ef8c69"), Value: mustParseString("115500000000000000000")},
	{Address: common.HexToAddress("0xd32C0812Fa1296F082671D5Be4CbB6bEeedC2397"), Value: mustParseString("10000000000000000000")},
	{Address: common.HexToAddress("0xd61a48b0e11B0Dc6b7Bd713B1012563c52591BAA"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xd802c6d127835279f85ebcfada7916237a549deb"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xe6eA85F6dA9F3Fad3Df294Bd62c3091Dcc2cFBed"), Value: mustParseString("1500000000000000000")},
	{Address: common.HexToAddress("0xe877FcB4b26036Baa44d3E037117b9e428B1Aa65"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xeF61c2a4F899Cf2D64AF23Dfd7c51F83696D25f7"), Value: mustParseString("500000000000000000")},
	{Address: common.HexToAddress("0xf41d3430ab8fb0c06c5bbf9efca587c33cdcfae3"), Value: mustParseString("500000000000000000")},
}

var PiccadillyNTNallocs = []struct {
	Address common.Address
	Value   *big.Int
}{
	{Address: common.HexToAddress("0x05C2ee5d563E75E431649CaECE1a598f862e5B02"), Value: mustParseString("3397749666666670000000000")},
	{Address: common.HexToAddress("0x141AE1933A38D329A03cee280375815A5dE8e93b"), Value: mustParseString("16133220000000000000000")},
	{Address: common.HexToAddress("0x25B456f817B645B8f8Fd9d2A5C499B279aA12a2f"), Value: mustParseString("50000000000000000000000")},
	{Address: common.HexToAddress("0x283c747f683375D80cA3050a37b1B14f6d243d07"), Value: mustParseString("64532880000000000000000")},
	{Address: common.HexToAddress("0x3F3FeE9C908c43138d7e892CE33cAF85BDEc83e6"), Value: mustParseString("169375000000000000000000")},
	{Address: common.HexToAddress("0x58F39270B5469b94914b96231da30D3DFB9cfEa8"), Value: mustParseString("60000000000000000000000")},
	{Address: common.HexToAddress("0x6d49071fb4D3eC08b99e89Bb06208B5FA8cF7907"), Value: mustParseString("395208333333330000000000")},
	{Address: common.HexToAddress("0x8b914020A7099E4723f45561E897fa2740885A55"), Value: mustParseString("4600000000000000000000000")},
	{Address: common.HexToAddress("0xC2e1FBc007aE179c2EE9ED60E3CCe7087c35C749"), Value: mustParseString("37644180000000000000000")},
	{Address: common.HexToAddress("0xaeD49e2A958F08338079294B2bC1E512eeB87914"), Value: mustParseString("13550000000000000000000000")},
	{Address: common.HexToAddress("0xb3fDCffE7863b5a450eB68E6dfda8Bc0f97EDb66"), Value: mustParseString("40000000000000000000000")},
	{Address: common.HexToAddress("0xb5678C419aB603cFdf2a33589Bb7E5B73c7d2dC6"), Value: mustParseString("16666666666670000000000")},
	{Address: common.HexToAddress("0xd22dE8e1720E1e6eb8Cb846259848e0627Ef8c69"), Value: mustParseString("150576720000000000000000")},
}

var PiccadillyLSNTNallocs = []struct {
	Address common.Address
	Value   *big.Int
}{
	{Address: common.HexToAddress("0x05C2ee5d563E75E431649CaECE1a598f862e5B02"), Value: mustParseString("17633333333333300000000000")},
	{Address: common.HexToAddress("0x25B456f817B645B8f8Fd9d2A5C499B279aA12a2f"), Value: mustParseString("1150000000000000000000000")},
	{Address: common.HexToAddress("0x58F39270B5469b94914b96231da30D3DFB9cfEa8"), Value: mustParseString("1380000000000000000000000")},
	{Address: common.HexToAddress("0xb3fDCffE7863b5a450eB68E6dfda8Bc0f97EDb66"), Value: mustParseString("920000000000000000000000")},
	{Address: common.HexToAddress("0xb5678C419aB603cFdf2a33589Bb7E5B73c7d2dC6"), Value: mustParseString("383333333333330000000000")},
}

var PiccadillyLNSNTNallocs = []struct {
	Address common.Address
	Value   *big.Int
}{
	{Address: common.HexToAddress("0x3F3FeE9C908c43138d7e892CE33cAF85BDEc83e6"), Value: mustParseString("3895625000000000000000000")},
	{Address: common.HexToAddress("0x6d49071fb4D3eC08b99e89Bb06208B5FA8cF7907"), Value: mustParseString("9089791666666700000000000")},
}

var PiccadillyGVNTNallocs = []struct {
	Address common.Address
	Value   *big.Int
}{
	{Address: common.HexToAddress("0x100E38f7BCEc53937BDd79ADE46F34362470577B"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x197B2c44b887c4aC01243BDE7E4bBa8bd95BC3a8"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x1Be7f70BCf8393a7e4A5BcC66F6f15d6e35cfBBC"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x3597d2D42f8Fbbc82E8b1046048773aD6DDB717E"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x36142A4f36974e2935192A1111C39330aA296D3C"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x23b4Be9536F93b8D550214912fD0e38417Ff7209"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x383A3c437d3F12f60E5fC990119468D3561EfBfc"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x3fe573552E14a0FC11Da25E43Fef11e16a785068"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x527192F3D2408C84087607b7feE1d0f907821E17"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x551f3300FCFE0e392178b3542c009948008B2a9F"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x5E17e837DcBa2728C94f95c38fA8a47CB9C8818F"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x6747c02DE7eb2099265e55715Ba2E03e8563D051"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x718361fc3637199F24a2437331677D6B89a40519"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x725fC5416BDb173642D21DfC401519B0DCBf7f3b"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x8f91e0ADF8065C3fFF92297267E02DF32C2978FF"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x94470A842Ea4f44e668EB9C2AB81367b6Ce01772"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x94d28f08Ff81A80f4716C0a8EfC6CAC2Ec74d09E"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x99E2B4B27BDe92b42D04B6CF302cF564D2C13b74"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x9C7dAABb5101623340C925CFD6fF74088ff5672e"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0x9d28e40e9ec4789f9a0d17e421f76d8d0868ea44"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xA284470fa70D8A2A8402054e40A36077fEAdCF51"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xBBf36374eb23968F25aecAEbb97BF3118f3c2fEC"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xBE287C82A786218E008FF97320b08244BE4A282c"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xDCA5DFF3D42f2db3C18dBE823380A0A81db49A7E"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xE4686A4C6E63A8ab51B458c52EB779AEcf0B74f7"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xEf0Ba5e345C2C3937df5667A870Aae5105CAa3a5"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xcdEed21b471b0Dc54faF74480A0E700fCc42a7b6"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xcf716b3930d7cf6f2ADAD90A27c39fDc9D643BBd"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xd61a48b0e11B0Dc6b7Bd713B1012563c52591BAA"), Value: mustParseString("1000000000000000000")},
	{Address: common.HexToAddress("0xe877FcB4b26036Baa44d3E037117b9e428B1Aa65"), Value: mustParseString("1000000000000000000")},
}

var PiccadillySDPDelegations = []struct {
	Address common.Address
	Value   *big.Int
}{
	{Address: common.HexToAddress("0x100E38f7BCEc53937BDd79ADE46F34362470577B"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x197B2c44b887c4aC01243BDE7E4bBa8bd95BC3a8"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x1Be7f70BCf8393a7e4A5BcC66F6f15d6e35cfBBC"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x3597d2D42f8Fbbc82E8b1046048773aD6DDB717E"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x36142A4f36974e2935192A1111C39330aA296D3C"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x23b4Be9536F93b8D550214912fD0e38417Ff7209"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x383A3c437d3F12f60E5fC990119468D3561EfBfc"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x3fe573552E14a0FC11Da25E43Fef11e16a785068"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x527192F3D2408C84087607b7feE1d0f907821E17"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x551f3300FCFE0e392178b3542c009948008B2a9F"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x5E17e837DcBa2728C94f95c38fA8a47CB9C8818F"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x6747c02DE7eb2099265e55715Ba2E03e8563D051"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x718361fc3637199F24a2437331677D6B89a40519"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x725fC5416BDb173642D21DfC401519B0DCBf7f3b"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x8f91e0ADF8065C3fFF92297267E02DF32C2978FF"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x94470A842Ea4f44e668EB9C2AB81367b6Ce01772"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x94d28f08Ff81A80f4716C0a8EfC6CAC2Ec74d09E"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x99E2B4B27BDe92b42D04B6CF302cF564D2C13b74"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x9C7dAABb5101623340C925CFD6fF74088ff5672e"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0x9d28e40e9ec4789f9a0d17e421f76d8d0868ea44"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0xA284470fa70D8A2A8402054e40A36077fEAdCF51"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0xBBf36374eb23968F25aecAEbb97BF3118f3c2fEC"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0xBE287C82A786218E008FF97320b08244BE4A282c"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0xDCA5DFF3D42f2db3C18dBE823380A0A81db49A7E"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0xE4686A4C6E63A8ab51B458c52EB779AEcf0B74f7"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0xEf0Ba5e345C2C3937df5667A870Aae5105CAa3a5"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0xcdEed21b471b0Dc54faF74480A0E700fCc42a7b6"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0xcf716b3930d7cf6f2ADAD90A27c39fDc9D643BBd"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0xd61a48b0e11B0Dc6b7Bd713B1012563c52591BAA"), Value: mustParseString("100000000000000000000000")},
	{Address: common.HexToAddress("0xe877FcB4b26036Baa44d3E037117b9e428B1Aa65"), Value: mustParseString("100000000000000000000000")},
}

var PiccadillyGenesisValidators = []struct {
	ValidatorAddress common.Address
	Treasury         common.Address
	OracleAddress    common.Address
	ConsensusKey     []byte
	Enode            string
	BondedStake      *big.Int
}{
	// 1dNXef
	{
		ValidatorAddress: common.HexToAddress("0x3597d2D42f8Fbbc82E8b1046048773aD6DDB717E"),
		Treasury:         common.HexToAddress("0xc1cbD63f219F39b41340ea3Dac320c22894bcC2e"),
		OracleAddress:    common.HexToAddress("0x842E176AF41eC98e3269FB752a17840d0589a2e5"),
		ConsensusKey:     common.FromHex("0x987e729178b455c34051ba097a3a61e0a6164abc00e48bd24bc6dbe23b33571555691071f475145b4fce09a1d8c6f60b"),
		Enode:            "enode://64004f2176e58b0162fac745abbb6efd8b8f6edb761673d3e288005fb53d9eea6725e44327a50b97e87fe5e48da2495f69f70138d26a45aa2d692564a031c8e8@160.250.106.31:30303",
		BondedStake:      Ntn1,
	},
	// 5AYduf
	{
		ValidatorAddress: common.HexToAddress("0x99E2B4B27BDe92b42D04B6CF302cF564D2C13b74"),
		Treasury:         common.HexToAddress("0xE052e6B778C2b9591548217C3372897513175684"),
		OracleAddress:    common.HexToAddress("0xaDF6a07D1f9D52bd9a464C8e3B1B670FD4b2cC55"),
		ConsensusKey:     common.FromHex("0xb2eed3ac8ec307e0862cdf7b8435049a98d8c83721a6066308ec57a1d9ec7f9c4e4725872dbfc96a83d102a77b430eb0"),
		Enode:            "enode://a20e27effd92dc11e7340e96a6f2908124ea363e6b68af34cad2a46a9ffdc6f5d4f516acec7f98949cc25955269f7842dc513444902c21239155de7e70b86a87@65.21.47.31:30303",
		BondedStake:      Ntn1,
	},
	// 7La9VU
	{
		ValidatorAddress: common.HexToAddress("0xcf716b3930d7cf6f2ADAD90A27c39fDc9D643BBd"),
		Treasury:         common.HexToAddress("0xC686DD5e936Be7a2491DC66689dba7ebe6A049eF"),
		OracleAddress:    common.HexToAddress("0x42B683087647378Ea10323e415dCA76604D56d34"),
		ConsensusKey:     common.FromHex("0xb55ff748491cc9f24725e6db2ac4e5393a8d0428de9c84cedd48d908c19ad4c3ab5160999f0fbaa2db044bf9f1ca1ded"),
		Enode:            "enode://cff5b54f5afac836d0577ebd497b4dc754d167f02ba77498dfcc32046eb30273011658840e54797884bb4e047f0231b5405c8b9997a50a166534c00de5d385ab@85.10.207.218:30303",
		BondedStake:      Ntn1,
	},
	// aB3kT6
	{
		ValidatorAddress: common.HexToAddress("0x718361fc3637199F24a2437331677D6B89a40519"),
		Treasury:         common.HexToAddress("0x52a7c9895545c6e6b221af7a2ac708f0eefa09fd"),
		OracleAddress:    common.HexToAddress("0x0aB543903ff68F1CdF948D3bDEf0706C14eAaB9B"),
		ConsensusKey:     common.FromHex("0xa5e5189151fd06c91c11943cd1c861a0bf801f4feffe290284edec8d848d6078b2f216e6098efb1c4b4d615c735facc8"),
		Enode:            "enode://bce186f2b956818d96b80293b8a78233c77daa84004e33304ed55ece1c6650b7a3a21249b005d362ff8c5fb919d7c8ac707e075b24379d3252be558fc16a83f2@51.159.206.200:62222",
		BondedStake:      Ntn1,
	},
	// BjcS9s
	{
		ValidatorAddress: common.HexToAddress("0x94d28f08Ff81A80f4716C0a8EfC6CAC2Ec74d09E"),
		Treasury:         common.HexToAddress("0xa7705415B06e76075982C7e8BaCa4aAF3D6d0f28"),
		OracleAddress:    common.HexToAddress("0x469C4A81d86461d1E85be1741b1a3152e5BB9b98"),
		ConsensusKey:     common.FromHex("0x86f21aa126b2bae0aca1926ae5ed55f2d0207917ca6995bd48755f809868b8903e56e4cfe48bee22224e854f2e7ffb2e"),
		Enode:            "enode://46f4abe3aeca863ce3a1b4a2b2fce3112476ca75a20039ef4bad78e1a2171ae36404d74b08a0c5a8720e2548d296d37e0b92062c096801b3f6d2d86e4e9da2f2@65.108.206.118:30303",
		BondedStake:      Ntn1,
	},
	// buSlFR
	{
		ValidatorAddress: common.HexToAddress("0x383A3c437d3F12f60E5fC990119468D3561EfBfc"),
		Treasury:         common.HexToAddress("0x8B458386eac12f4E16d23e74b3c19AF0B04812bB"),
		OracleAddress:    common.HexToAddress("0x8B458386eac12f4E16d23e74b3c19AF0B04812bB"),
		ConsensusKey:     common.FromHex("0x89f62c1858723ed3d027d31026e37d6edfdf730e21a9315a1f4e54c50b363f341f88ee5b420606cce4ab124bfaa6c496"),
		Enode:            "enode://5661ce15c8ecf06fd77bc5a33d2b687a4b03529b0d2964b1df6081d6600fd538795f7ab2ca160c46c96de9f1fa0255bad3d007f34f23184809d7870b66475e69@213.239.214.182:30303",
		BondedStake:      Ntn1,
	},
	// C5h4Wf
	{
		ValidatorAddress: common.HexToAddress("0xe877FcB4b26036Baa44d3E037117b9e428B1Aa65"),
		Treasury:         common.HexToAddress("0x9691e63e8e90deCa91600502b6E040aDeD3d6503"),
		OracleAddress:    common.HexToAddress("0x9691e63e8e90deCa91600502b6E040aDeD3d6503"),
		ConsensusKey:     common.FromHex("0xb96706e536cdc9a38d3d9e570cd1bc2bb2316a04e3d9c5a042970128833dfc8a8585222ed2c8ba86cbfd1e9477a4cf10"),
		Enode:            "enode://b9c39abeebc9b883875e88efc49c1f818e41fae7e19fac6c267f5f453d71b437f6f2f8756be5204138d45f4a2027fc3bf85991b1dd6f3c99b6cec46ec0349546@14.243.91.37:30303",
		BondedStake:      Ntn1,
	},
	// D0s608
	{
		ValidatorAddress: common.HexToAddress("0xDCA5DFF3D42f2db3C18dBE823380A0A81db49A7E"),
		Treasury:         common.HexToAddress("0x3d805a3f9efd6f5183aceddd7d531a9c37cb43cc"),
		OracleAddress:    common.HexToAddress("0x96841a9441ded4eb282e196b5a9b824d870c97e3"),
		ConsensusKey:     common.FromHex("0xb49dfa4ce7fdddbd99e6c80fc1f52bc57c732cbe2793d60d4930455153a78c53d96450e0c209b59fdfe1f535d59d7987"),
		Enode:            "enode://bdc0f36715898658115138fc3b963db5e5c69e79192cd5e2e6ec60679859b18a0a0ba77aeb89f5facc7995f43b87d04fe74626968415d09835cc5feb6707bb3b@135.181.246.250:19440",
		BondedStake:      Ntn1,
	},
	// DHnnFt
	{
		ValidatorAddress: common.HexToAddress("0x3fe573552E14a0FC11Da25E43Fef11e16a785068"),
		Treasury:         common.HexToAddress("0xFf02373228e1133Da0a16340350532b813f463Dc"),
		OracleAddress:    common.HexToAddress("0x9Cf765e8D8D3355956Dd7EE757bda5244A944a20"),
		ConsensusKey:     common.FromHex("0x96843bfb82f6b5860aaa93d59b81ac8e08e0ff9f5a76c25e5e5e3bb127ca06d0cffb19fabb4e25305c6be4ad18c7ac7b"),
		Enode:            "enode://b538d70d1195f78020cbe634d178e7ba572416aff996a93e17269c30b127a4a6d991421379ecdaa342ed93d70935910c5287aade585a68c85d89d8c2d1a503d7@46.105.223.86:11703",
		BondedStake:      Ntn1,
	},
	// DK29qE
	{
		ValidatorAddress: common.HexToAddress("0x551f3300FCFE0e392178b3542c009948008B2a9F"),
		Treasury:         common.HexToAddress("0x75474aC55768fAb6fE092191eea8016b955072F5"),
		OracleAddress:    common.HexToAddress("0x6c5AE53a803796D788E917D1fE919BfC8B56d2E6"),
		ConsensusKey:     common.FromHex("0xa3aa75e42e99275f7d7985538fedc06e7f128b138a5311702afc0dc129484763645c40c36fdd97ff0d0293b00a031714"),
		Enode:            "enode://772248dfe1af5f77e0efc0510e83364bfad55cbd6d3e276f3bd0b4ddec6472aa98645655fd80bbf049ba3da18d219ab30a68fcb98da8e06dd42863dd0356cc95@35.242.168.170:30303",
		BondedStake:      Ntn1,
	},
	// eO6oqk
	{
		ValidatorAddress: common.HexToAddress("0x527192F3D2408C84087607b7feE1d0f907821E17"),
		Treasury:         common.HexToAddress("0xe6eA85F6dA9F3Fad3Df294Bd62c3091Dcc2cFBed"),
		OracleAddress:    common.HexToAddress("0xe6eA85F6dA9F3Fad3Df294Bd62c3091Dcc2cFBed"),
		ConsensusKey:     common.FromHex("0xad6575bb260db0b73572ad023d41fdb101a52f2e6be302cd0a79cb6dc23a5d8cce9195033cfb76d2933a55fb34bd7b48"),
		Enode:            "enode://4b57bf8eccd5b087fb9d2d9d3d4d9ff06a47dfa9fc26e6c768c36167dfc3ea5c2f6508c8bcb9d092c6327ad28faa1a2add25b41a91a895a8e2b6810386f14a03@20.197.19.241:30303",
		BondedStake:      Ntn1,
	},
	// GxHedr
	{
		ValidatorAddress: common.HexToAddress("0x9d28e40e9ec4789f9a0d17e421f76d8d0868ea44"),
		Treasury:         common.HexToAddress("0x21ba84e40d5d3ae610078d287e336547570aa3fa"),
		OracleAddress:    common.HexToAddress("0x0804A922ba6B7c0965928a8d9A10ecdeA0b3c41A"),
		ConsensusKey:     common.FromHex("0xae6013d1ad0f8e1a1ed62c68ff3ef09461e32e95a7f5f4ded6b9fb4dc7f866a5984727e8214fc92e85906df4627625a2"),
		Enode:            "enode://da17996c8380116d93b3615489e2fb3606d0fd21fcee728dee2fd1cdd2060441fa85657116ece5b29218f3a2e61a3204de57b3704b4976a4f69b3bed440b5a7b@45.153.35.148:30303",
		BondedStake:      Ntn1,
	},
	// HrLoXr
	{
		ValidatorAddress: common.HexToAddress("0x1Be7f70BCf8393a7e4A5BcC66F6f15d6e35cfBBC"),
		Treasury:         common.HexToAddress("0xc175508b966bd5294d1d9bb2ffeec96b68945817"),
		OracleAddress:    common.HexToAddress("0x345de4128c57d4c9977e958ef5cbaf133d3041f6"),
		ConsensusKey:     common.FromHex("0x8e37252fc62b32896b522150a020170fbd937a9871967e3a17cc4c9941a5dceeca881eb21316e42c7cc56e3dc3fc099a"),
		Enode:            "enode://379eb97a0420342d9be882e288f0cf63aa537cb7fd39e2294d53b979533fd4c43aac2e4340cb0abb72f70616c46fc89f4cba03eb60354191259f3bd8d06d8442@65.109.154.189:30303",
		BondedStake:      Ntn1,
	},
	// Ilg5ne
	{
		ValidatorAddress: common.HexToAddress("0x5E17e837DcBa2728C94f95c38fA8a47CB9C8818F"),
		Treasury:         common.HexToAddress("0x6636f811F6bfF4e2ce43A9a5009ae669eB8d9c5f"),
		OracleAddress:    common.HexToAddress("0xC9C7d1fA7adFb2856bB2F77f9F80fEa5F5a5073d"),
		ConsensusKey:     common.FromHex("0xb92b96a0bdd7d57836e326af33b40f5532f10e0268a61205acf568efc63a62391ac0debeeb04b1cdffaf9c58057d00e6"),
		Enode:            "enode://d9cfb537ee18b2f291216a2ee9706594ce56688d39a20a906b181c59fca33ec838aa7a8e93946a33c0a632db448159f1bdb4d947c250998bf295c387464fd223@195.3.223.135:30303",
		BondedStake:      Ntn1,
	},
	// J4mPq8
	{
		ValidatorAddress: common.HexToAddress("0x36142A4f36974e2935192A1111C39330aA296D3C"),
		Treasury:         common.HexToAddress("0xb41Ef07Ae29c45b9d7daB1a4608B1157E5D97B01"),
		OracleAddress:    common.HexToAddress("0x1f4b17C565e88d152e06A3938ca5830f7FFe6107"),
		ConsensusKey:     common.FromHex("0xb4658589fd31bafa3f1c91057c002546faa13f0129e9336402f87144f9ce143e88c6f9caffe7382a08b7447845567ad4"),
		Enode:            "enode://fc8edc5395f74c76bcfacabe3854ac0d5f77683deb247672d27dc06ceed9eed05deb26cf3ec8fd36b99d4ce2789f683d9dd258c2165c63081294ccc23fa087c2@167.235.177.151:30303",
		BondedStake:      Ntn1,
	},
	// L9bXw2
	{
		ValidatorAddress: common.HexToAddress("0x23b4Be9536F93b8D550214912fD0e38417Ff7209"),
		Treasury:         common.HexToAddress("0x9058AfE8910fAD6941B0D743F4db5A8EE987638F"),
		OracleAddress:    common.HexToAddress("0xa32a0cad4A19AF125dB862C28382c8C83939747c"),
		ConsensusKey:     common.FromHex("0xa75b87984e7fe44699c94e5cdaf43036b9b3ddd358e7d84d319ca5b8c892abf466f73139d4940b0753fb135d7d574856"),
		Enode:            "enode://e1a394c45de80d71d7d8cd8b77812bdea31a06faa03ec07f0ad060cd8e9debcb3262d6a2c0d1b4da97d579e9c697ee9c59a665867faa298a7fff36bd3e890d7c@65.109.92.163:30303",
		BondedStake:      Ntn1,
	},
	// L9RwkS
	{
		ValidatorAddress: common.HexToAddress("0x6747c02DE7eb2099265e55715Ba2E03e8563D051"),
		Treasury:         common.HexToAddress("0x1ef06a40f656feac2fd936adf1da3bea61040589"),
		OracleAddress:    common.HexToAddress("0xd802c6d127835279f85ebcfada7916237a549deb"),
		ConsensusKey:     common.FromHex("0xa286ee63600c630ce7c63d86c2eb83355e4025684b37cc3b00e835a02b7a430638f3c245c06c34a85ee259fe0ccf60ef"),
		Enode:            "enode://8cd4f752ebebc645c2a8b0f7c538c3298df9332e2adbfc8bac8f609cc2f3cd17ebf11b62ddeb5c0c8e4c1dcf58d87f7d2a00c20207ef79ed6fabca0b9092ecc4@162.19.169.74:30303",
		BondedStake:      Ntn1,
	},
	// lvlO3g
	{
		ValidatorAddress: common.HexToAddress("0xd61a48b0e11B0Dc6b7Bd713B1012563c52591BAA"),
		Treasury:         common.HexToAddress("0xC0C483D9ABf549B73a2b6CfcFB2228321D15B25c"),
		OracleAddress:    common.HexToAddress("0x4c879c150463bb14c8B2e2307649E5Cd6BB4BDcE"),
		ConsensusKey:     common.FromHex("0x93161d72e966d1705b5dcafcf0038a7c5d1f2d33ba7f1a351da6ef52c0d559b7c8687a60fa480e57e2f76a7f85d51094"),
		Enode:            "enode://4981de1baa14d56f9c7d30457786c3da1e594d6bf70daf789aec8c8b92c5b3ff78da19963f03115bf49d2c447af3cafb5831a1d768c0c53199eb021844b39291@185.165.243.24:30303",
		BondedStake:      Ntn1,
	},
	// NBXpxO
	{
		ValidatorAddress: common.HexToAddress("0xBBf36374eb23968F25aecAEbb97BF3118f3c2fEC"),
		Treasury:         common.HexToAddress("0x11985c0b0C2df87f83Ba84b9a95C7C13e81c3a36"),
		OracleAddress:    common.HexToAddress("0x9Af67224C16C6cAb7ef22A239329532325223A7c"),
		ConsensusKey:     common.FromHex("0xa70a21a1d5896ad8b348c931e24810c1238d100db876d686105796d1a9af77d0c93b52d8070e0fd65cc12c7ed74c0401"),
		Enode:            "enode://3ec4e57adf353c0981496c9891b0e1556f756d66260e8dc5822967c367ea001876e86eaf2309350e7cf4c4d410bba01c425291246483079c5c9be272ae7971b0@64.176.54.103:30303",
		BondedStake:      Ntn1,
	},
	// pYcWqU
	{
		ValidatorAddress: common.HexToAddress("0x8f91e0ADF8065C3fFF92297267E02DF32C2978FF"),
		Treasury:         common.HexToAddress("0x94CdeEfB31Dd0d430A3430e0680569714B115d4F"),
		OracleAddress:    common.HexToAddress("0xc945bC0C9A803864008e0A738Ed4e2CC523aE0D3"),
		ConsensusKey:     common.FromHex("0xa6c19cc2771aee5bb4e21c9c7a234046dbd1b45b330294ca02445eedebab3f02d16a0b5602e1f1403078e97c00d29bd2"),
		Enode:            "enode://2352fd3893515b22500d573dba60a4b6bc64890f8758600d9f99652de13b54733ffc8b6d1d6a89debe97b639224334a50af438328fd964d30351514c6377eef0@37.252.186.198:30303",
		BondedStake:      Ntn1,
	},
	// q0QnDh
	{
		ValidatorAddress: common.HexToAddress("0xcdEed21b471b0Dc54faF74480A0E700fCc42a7b6"),
		Treasury:         common.HexToAddress("0xD6ed4dC54E1AA7A1cF5a925afAdb177133600566"),
		OracleAddress:    common.HexToAddress("0xc7dD8483e3dFAE05D0D86302382cc98E7F2706f0"),
		ConsensusKey:     common.FromHex("0x86d048b1a123a2e74c7e4998bafcecb49fd16f366d5709478e654a85ac3c8add474653b39f8fc32614e567b52fba0d85"),
		Enode:            "enode://16e03c2b767f1f63f44d68ce2ce67c35910aca4f57b05e9a42330ee4dd739b0d339c0309d187fe006559f1ffddc68ebca77e8a5f5fa3fc173998978d8410c382@65.109.111.234:30304",
		BondedStake:      Ntn1,
	},
	// q7Z1nS
	{
		ValidatorAddress: common.HexToAddress("0xBE287C82A786218E008FF97320b08244BE4A282c"),
		Treasury:         common.HexToAddress("0x1A9295c64508490B81285E7EAf64b6788383D8CC"),
		OracleAddress:    common.HexToAddress("0xc8A6e810C8Ae52b7937C7b5756B80328172c022E"),
		ConsensusKey:     common.FromHex("0x8afe7050848e51433a30561efc0eb1d40698e3880b496b6cbcce1c35ca748575345605877298b480b4adde5bc96c9767"),
		Enode:            "enode://ac83a7eed6b79e066a4bdfbc8feda7ee33e2269652ce694311a65905a80a3159789e662b9416e108fc95d030d06067361835717c09aae5e9293a8e2c0bd6ba74@103.167.234.109:30303",
		BondedStake:      Ntn1,
	},
	// Qlb0W3
	{
		ValidatorAddress: common.HexToAddress("0x100E38f7BCEc53937BDd79ADE46F34362470577B"),
		Treasury:         common.HexToAddress("0x5b9C621E304ef826eb94f554f85447F1e358Cb66"),
		OracleAddress:    common.HexToAddress("0xc87d6957b5E7d3B268282630042037Bd873eC652"),
		ConsensusKey:     common.FromHex("0xa6b9f7113a95aa40a26571f4e26f2a971910c6ff8b067dccee61e53108868f36afc0c79ed4f8dd972c5d0085181abfdb"),
		Enode:            "enode://291f1307c0daee6a0fdfa227bb8cc2e30fe1a0dd30ea61e976dc76d7acbeb6774acdbb1f35d5b9e5ff1ed348314e535eb63b242d1f8ad6378fb0f4d34abc11a0@5.57.42.20:30303",
		BondedStake:      Ntn1,
	},
	// qOe4W1
	{
		ValidatorAddress: common.HexToAddress("0xEf0Ba5e345C2C3937df5667A870Aae5105CAa3a5"),
		Treasury:         common.HexToAddress("0x6B5b2750A59ff6Fc7B087d21454761e4C33E218B"),
		OracleAddress:    common.HexToAddress("0x0916e717fcDBD625A99DfA468142D3EB251f6b5A"),
		ConsensusKey:     common.FromHex("0xb30755eb557b8908b7ed46669b814189615fd7428de1c5d53eae7459aa34cbc308a7731abfeca02d2e2ee6dfa298f463"),
		Enode:            "enode://f84a192597597c98c6218ebab4ec10ad03fe7f69bc1920217562b71760a626d91639c0d2ef467ff06ee9210814b776b2392d06df9f230d52013fbfcaaccdcb72@35.214.255.214:30303",
		BondedStake:      Ntn1,
	},
	// Tgcs7W
	{
		ValidatorAddress: common.HexToAddress("0x725fC5416BDb173642D21DfC401519B0DCBf7f3b"),
		Treasury:         common.HexToAddress("0xb7d8925BA077E89C1227Aa985de25d4ccC52F892"),
		OracleAddress:    common.HexToAddress("0x1cb9651394794b8F9948590973D591c262929AE6"),
		ConsensusKey:     common.FromHex("0x88dfd07a93c63943841d66698c52b3f5197aaf3af6dcc538edd5a4ea653290fee64c8ceafda84d81bf5ab0a0e384d594"),
		Enode:            "enode://e7cea14b38d590066217b6639ee24f964b5ec3f5db127e460b695562495f5d04d2063b71a86baeaddbf318d204e4322dee2271c9dbcf462650f2547233fd2f67@178.205.102.224:30303",
		BondedStake:      Ntn1,
	},
	// tqXbRw
	{
		ValidatorAddress: common.HexToAddress("0x94470A842Ea4f44e668EB9C2AB81367b6Ce01772"),
		Treasury:         common.HexToAddress("0x2F8cEa90D5d8Eff154fe85841C771Ac33bB6EEb1"),
		OracleAddress:    common.HexToAddress("0xf41d3430ab8fb0c06c5bbf9efca587c33cdcfae3"),
		ConsensusKey:     common.FromHex("0x93d58b3114509a592c321250cb5a512f42aa19e59dfa29aec90a262fa0dbb9364e138caff57bc4efe5fe27c05bfe6d4a"),
		Enode:            "enode://700ae526623b87a748acf278cee299d970ccde4e4d6e7aa7685f4a550500b6e53b84892e37c2c10516673f45253fcb824d8e1836ee91a92a16b66b85b8000642@5.199.172.61:30303",
		BondedStake:      Ntn1,
	},
	// TyXZGk
	{
		ValidatorAddress: common.HexToAddress("0x197B2c44b887c4aC01243BDE7E4bBa8bd95BC3a8"),
		Treasury:         common.HexToAddress("0x526508c671eBD5311ebc3967Ac3F1D445907cC67"),
		OracleAddress:    common.HexToAddress("0x9C93Fe8e41137c4a23D8e525E2fa1b71e25b9252"),
		ConsensusKey:     common.FromHex("0xae1b49d79c320203b526e79a82f744b3c0ab2a270f1f8bc30db9e54e0ad08053e94bd0848b515175985d62f5105c7403"),
		Enode:            "enode://12f6c78046f38b683f7aa673778d81598418f88f6642cbbca30da4627336acc40aea25454a651a552cf1a3527b610bbc3518806f34bde8f531530efaf1ca3cd8@173.231.43.98:14403",
		BondedStake:      Ntn1,
	},
	// ULaZrL
	{
		ValidatorAddress: common.HexToAddress("0xE4686A4C6E63A8ab51B458c52EB779AEcf0B74f7"),
		Treasury:         common.HexToAddress("0xA8568B1f1E927E4d1AA4c0D248A3a9FFDD33A0dE"),
		OracleAddress:    common.HexToAddress("0x8f2c0eB1Ac36E74196E2cF8aBe3aF346105d1B0a"),
		ConsensusKey:     common.FromHex("0x8375584b6108dc57307d8b2335d01286f96198b829bcaa1c2ad30545cacbdf7886b1cf12e8af1cc4e585fa189b8f3995"),
		Enode:            "enode://842c8b458c2efb481cddbf412b7c712e6c1511bb170bb2a7c8c51f3aa631001651640b2083edd342b58d84e0e882b2a4ee71b9a5c1894068bea222470c4b9d44@37.27.123.37:30303",
		BondedStake:      Ntn1,
	},
	// vd73Er
	{
		ValidatorAddress: common.HexToAddress("0xA284470fa70D8A2A8402054e40A36077fEAdCF51"),
		Treasury:         common.HexToAddress("0x618CfCF7f73230552BE701fc1eBd835fA17e2d26"),
		OracleAddress:    common.HexToAddress("0xeF61c2a4F899Cf2D64AF23Dfd7c51F83696D25f7"),
		ConsensusKey:     common.FromHex("0xb22e3a21177e85b6a37bf039ac795859091087131c3cc51491c4fe8c4fdf920cf7dce804cbd88190af57615ae8dd4854"),
		Enode:            "enode://eda932bcdc47f31b10d5fd9e397a6dd2377aa48d14836fcb8ebe6c14b0681b4ef0c8a4fcdbaf7dfce1235a44fdc1e558e77dc40fb44df7991c4c9488b0bb52b9@54.195.150.136:30303",
		BondedStake:      Ntn1,
	},
	// WHgEhi
	{
		ValidatorAddress: common.HexToAddress("0x9C7dAABb5101623340C925CFD6fF74088ff5672e"),
		Treasury:         common.HexToAddress("0xC3B81e3f879C082a96Cad0cF0855F91847a64B31"),
		OracleAddress:    common.HexToAddress("0x6A4ece3e7c830c5115d8321aE1c29B90a69C7855"),
		ConsensusKey:     common.FromHex("0xb579a7df6f44c54413e344657c4bf07117904b25361218b32414ff509fc5b199a1ab5fac7f50d2cfe46193c7e9f5abb5"),
		Enode:            "enode://6a8426e68cba8921ea596f3505ded7f71a107c1f73bf228398c0031cba44322a3f46c8c151a1580b9650062e5be915f907ef335f1c25e979027825b24002ef83@185.26.11.57:30303",
		BondedStake:      Ntn1,
	},
}
