#!/bin/sh

if [ -z "$1" ]; then
	echo "Usage: ./console <ws://... or wss://... url>"
	echo "E.G:   ./console ws://localhost:8546"
	exit 1
fi

if ! which node > /dev/null; then
	echo "nodejs is not installed"
	echo "for ubuntu or debian users try 'sudo apt-get install nodejs'"
	exit 1
fi

if ! which npm > /dev/null; then
	echo "npm is not installed"
	echo "for ubuntu or debian users try 'sudo apt-get install npm'"
	exit 1
fi

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
scriptdir=$(dirname "$script")

cd "$scriptdir";

# Npm list returns a 0 exit code only if the packate is installed.
if ! npm list web3 > /dev/null 2>&1; then
	npm install web3 --package-lock=false
else
	CHECK_OUTDATED=$(npm outdated web3 --package-lock=false)
	if [ -n "$CHECK_OUTDATED" ]; then
		npm update web3 --package-lock=false
	fi
fi

# Note the --experimental-repl-await doesn't take effect for the code executed with eval.
node -i ./script.js "$1"
