run:
  deadline: 20m
  timeout: 2m
  tests: true
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  skip-files:
    - core/genesis_alloc.go

modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goconst
    - gofmt
    - golint
    - interfacer
    - deadcode
    - govet
    - structcheck
    - misspell
    - megacheck
    - unconvert
    - unparam
    - varcheck
    - scopelint
    - nakedret
    - prealloc
    - gosec
    - ineffassign
    - depguard
    - typecheck

  disable-all: true

linters-settings:
  golint:
    min-confidence: 0
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    auto-fix: false
  govet:
    check-shadowing: true
    min-len: 3 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences

issues:
  exclude-rules:
    - path: crypto/blake2b/
      linters:
        - deadcode
    - path: crypto/bn256/cloudflare
      linters:
        - deadcode
    - path: p2p/discv5/
      linters:
        - deadcode
    - path: core/vm/instructions_test.go
      linters:
        - goconst
    - path: cmd/faucet/
      linters:
        - deadcode
