codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
ignore:
  - "**/*_mock.go"  # ignore mock files
  - "contracts/autonity/rpcclient/clien_gen.go"  # ignore generated client
coverage:
  status:
    project:
      default:
        target: 30%
        threshold: null
      tendermint:
        flags: tendermint
        target: 65%
flags:
  tendermint:
    paths:
      - consensus/tendermint
