ignore:
  - "**/*_mock.go"  # ignore mock files
coverage:
  status:
    project:
      default:
        target: 50%
        threshold: null
flags:
  tendermint:
    paths:
      - consensus/tendermint
