ignore:
  - "**/*_mock.go"  # ignore mock files
  - "**/*_gen.go"  # ignore gen files
coverage:
  status:
    project:
      default:
        target: 50%
        threshold: null
      tendermint:
        flags: tendermint
        target: 65%
flags:
  tendermint:
    paths:
      - consensus/tendermint
