ignore:
  - "**/*_mock.go"  # ignore mock files
  - "**/*_gen.go"  # ignore generated client
  - "**/mock*.go"
  - "**/*_simulator.go" # ignore fault_simulator.go for accountability integration test.
  - "**/*.^go"
coverage:
  precision: 2
  round: nearest

  status:
    patch: off
    project:
      default:
        target: 60%  # without counting the coverage rate of tendermint package triggered by e2e tests, unit test fall to 61.33%.

comment:
  behavior: default
