codecov:
  require_ci_to_pass: yes
ignore:
  - "**/*_mock.go"  # ignore mock files
  - "**/*_gen.go"  # ignore generated client
  - "**/mock*.go"
  - "**/*_mock.go"
coverage:
  status:
    project:
      default:
        target: 30%
        threshold: null
      tendermint:
        flags: tendermint
        target: 65%
flags:
  tendermint:
    paths:
      - consensus/tendermint
