ignore:
  - "**/*_mock.go"  # ignore mock files
  - "**/*_gen.go"  # ignore generated client
  - "**/mock*.go"
  - "**/*.^go"
coverage:
  precision: 2
  round: nearest

  status:
    patch:
      if_not_found: success
      if_ci_failed: success
      informational: true
      if_no_uploads: success
    project:
      default:
        if_not_found: success
        if_ci_failed: success
        informational: true
        if_no_uploads: success
      autonity:
        flags:
          - autonity
        target: 30%
        threshold: null
      tendermint:
        flags:
          - tendermint
        target: 65%

flags:
  tendermint:
    paths:
      - consensus/tendermint/
  autonity:
    paths:
      - ./

comment:
  behavior: default
