ignore:
  - "**/*_mock.go"  # ignore mock files
  - "**/*_gen.go"  # ignore generated client
  - "**/mock*.go"
  - "**/*.^go"
  - "**/docs/**/*"
coverage:
  precision: 2
  round: nearest

  status:
    patch: off
    project:
      default:
        target: 30%
        threshold: null
      tendermint:
        flags:
          - tendermint
        target: 65%
flags:
  tendermint:
    paths:
      - consensus/tendermint/

comment:
  behavior: default
  require_changes: yes