ignore:
  - "**/*_mock.go"  # ignore mock files
  - "**/*_gen.go"  # ignore generated client
  - "**/mock*.go"
  - "**/*_simulator.go" # ignore fault_simulator.go for accountability integration test.
  - "**/*.^go"
coverage:
  precision: 2
  round: nearest

  status:
    patch: off
    project:
      default:
        target: 70%

comment:
  behavior: default
