ignore:
  - "**/*_mock.go"  # ignore mock files
  - "**/*_gen.go"  # ignore generated client
  - "**/mock*.go"
  - "docs"
coverage:
  status:
    patch: off
    project:
      default: off
      autonity:
        flags:
          - autonity
        target: 30%
        threshold: null
      tendermint:
        flags:
          - tendermint
        target: 65%

flags:
  tendermint:
    paths:
      - consensus/tendermint/
  autonity:
    paths:
      - ./

comment:
  behavior: default
