# Support setting various labels on the final image
ARG COMMIT=""
ARG VERSION=""
ARG BUILDNUM=""

# Build Autonity in a stock Go builder container
FROM golang:1.24-alpine AS builder

RUN apk add --no-cache make git gcc libc-dev linux-headers perl-utils jq

ADD . /autonity
RUN cd /autonity && make all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /autonity/build/bin/* /usr/local/bin/

EXPOSE 8545 8546 20203 30303 30303/udp

# Add some metadata labels to help programatic image consumption
ARG COMMIT=""
ARG VERSION=""
ARG BUILDNUM=""

LABEL commit="$COMMIT" version="$VERSION" buildnum="$BUILDNUM"
