// Code generated by MockGen. DO NOT EDIT.
// Source: consensus/tendermint/backend/gossiper.go

// Package backend is a generated GoMock package.
package backend

import (
	reflect "reflect"

	common "github.com/autonity/autonity/common"
	consensus "github.com/autonity/autonity/consensus"
	message "github.com/autonity/autonity/consensus/tendermint/core/message"
	types "github.com/autonity/autonity/core/types"
	gomock "go.uber.org/mock/gomock"
)

// Mockrouter is a mock of router interface.
type Mockrouter struct {
	ctrl     *gomock.Controller
	recorder *MockrouterMockRecorder
}

// MockrouterMockRecorder is the mock recorder for Mockrouter.
type MockrouterMockRecorder struct {
	mock *Mockrouter
}

// NewMockrouter creates a new mock instance.
func NewMockrouter(ctrl *gomock.Controller) *Mockrouter {
	mock := &Mockrouter{ctrl: ctrl}
	mock.recorder = &MockrouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrouter) EXPECT() *MockrouterMockRecorder {
	return m.recorder
}

// Route mocks base method.
func (m *Mockrouter) Route(committee *types.Committee, msg message.Msg, from common.Address) ([]types.CommitteeMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Route", committee, msg, from)
	ret0, _ := ret[0].([]types.CommitteeMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Route indicates an expected call of Route.
func (mr *MockrouterMockRecorder) Route(committee, msg, from interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Route", reflect.TypeOf((*Mockrouter)(nil).Route), committee, msg, from)
}

// SetBroadcaster mocks base method.
func (m *Mockrouter) SetBroadcaster(broadcaster consensus.Broadcaster) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBroadcaster", broadcaster)
}

// SetBroadcaster indicates an expected call of SetBroadcaster.
func (mr *MockrouterMockRecorder) SetBroadcaster(broadcaster interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBroadcaster", reflect.TypeOf((*Mockrouter)(nil).SetBroadcaster), broadcaster)
}
