// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/autonity/autonity/common"
	"github.com/autonity/autonity/common/hexutil"
	"github.com/autonity/autonity/common/math"
)

var _ = (*accountMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (a Account) MarshalJSON() ([]byte, error) {
	type Account struct {
		Code          hexutil.Bytes                            `json:"code,omitempty"`
		Storage       map[storageJSON]storageJSON              `json:"storage,omitempty"`
		Balance       *math.HexOrDecimal256                    `json:"balance" gencodec:"required"`
		NewtonBalance *math.HexOrDecimal256                    `json:"newtonBalance"`
		Bonds         map[common.Address]*math.HexOrDecimal256 `json:"bonds"`
		Nonce         math.HexOrDecimal64                      `json:"nonce,omitempty"`
		PrivateKey    hexutil.Bytes                            `json:"secretKey,omitempty"`
	}
	var enc Account
	enc.Code = a.Code
	if a.Storage != nil {
		enc.Storage = make(map[storageJSON]storageJSON, len(a.Storage))
		for k, v := range a.Storage {
			enc.Storage[storageJSON(k)] = storageJSON(v)
		}
	}
	enc.Balance = (*math.HexOrDecimal256)(a.Balance)
	enc.NewtonBalance = (*math.HexOrDecimal256)(a.NewtonBalance)
	if a.Bonds != nil {
		enc.Bonds = make(map[common.Address]*math.HexOrDecimal256, len(a.Bonds))
		for k, v := range a.Bonds {
			enc.Bonds[k] = (*math.HexOrDecimal256)(v)
		}
	}
	enc.Nonce = math.HexOrDecimal64(a.Nonce)
	enc.PrivateKey = a.PrivateKey
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (a *Account) UnmarshalJSON(input []byte) error {
	type Account struct {
		Code          *hexutil.Bytes                           `json:"code,omitempty"`
		Storage       map[storageJSON]storageJSON              `json:"storage,omitempty"`
		Balance       *math.HexOrDecimal256                    `json:"balance" gencodec:"required"`
		Nonce         *math.HexOrDecimal64                     `json:"nonce,omitempty"`
		NewtonBalance *math.HexOrDecimal256                    `json:"newtonBalance"`
		Bonds         map[common.Address]*math.HexOrDecimal256 `json:"bonds"`

		PrivateKey *hexutil.Bytes `json:"secretKey,omitempty"`
	}
	var dec Account
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Code != nil {
		a.Code = *dec.Code
	}
	if dec.Storage != nil {
		a.Storage = make(map[common.Hash]common.Hash, len(dec.Storage))
		for k, v := range dec.Storage {
			a.Storage[common.Hash(k)] = common.Hash(v)
		}
	}
	if dec.Balance == nil {
		return errors.New("missing required field 'balance' for Account")
	}
	a.Balance = (*big.Int)(dec.Balance)
	if dec.NewtonBalance != nil {
		a.NewtonBalance = (*big.Int)(dec.NewtonBalance)
	}
	if dec.Bonds != nil {
		a.Bonds = make(map[common.Address]*big.Int, len(dec.Bonds))
		for k, v := range dec.Bonds {
			a.Bonds[k] = (*big.Int)(v)
		}
	}
	if dec.Nonce != nil {
		a.Nonce = uint64(*dec.Nonce)
	}
	if dec.PrivateKey != nil {
		a.PrivateKey = *dec.PrivateKey
	}
	return nil
}
