// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/autonity/autonity/common"
)

// MarshalJSON marshals as JSON.
func (h Header) MarshalJSON() ([]byte, error) {
	type Header struct {
		ParentHash     common.Hash    `json:"parentHash"       gencodec:"required"`
		UncleHash      common.Hash    `json:"sha3Uncles"       gencodec:"required"`
		Coinbase       common.Address `json:"miner"            gencodec:"required"`
		Root           common.Hash    `json:"stateRoot"        gencodec:"required"`
		TxHash         common.Hash    `json:"transactionsRoot" gencodec:"required"`
		ReceiptHash    common.Hash    `json:"receiptsRoot"     gencodec:"required"`
		Bloom          Bloom          `json:"logsBloom"        gencodec:"required"`
		Difficulty     *big.Int       `json:"difficulty"       gencodec:"required"`
		Number         *big.Int       `json:"number"           gencodec:"required"`
		GasLimit       uint64         `json:"gasLimit"         gencodec:"required"`
		GasUsed        uint64         `json:"gasUsed"          gencodec:"required"`
		Time           uint64         `json:"timestamp"        gencodec:"required"`
		Extra          []byte         `json:"extraData"        gencodec:"required"`
		MixDigest      common.Hash    `json:"mixHash"`
		Nonce          BlockNonce     `json:"nonce"`
		BaseFee        *big.Int       `json:"baseFeePerGas"`
		Committee      *Committee     `json:"committee"`
		ProposerSeal   []byte         `json:"proposerSeal"        gencodec:"required"`
		Round          uint64         `json:"round"               gencodec:"required"`
		CommittedSeals [][]byte       `json:"committedSeals"      gencodec:"required"`
		LastEpochBlock *big.Int       `json:"lastEpochBlock"      gencodec:"required"`
	}
	var enc Header
	enc.ParentHash = h.ParentHash
	enc.UncleHash = h.UncleHash
	enc.Coinbase = h.Coinbase
	enc.Root = h.Root
	enc.TxHash = h.TxHash
	enc.ReceiptHash = h.ReceiptHash
	enc.Bloom = h.Bloom
	enc.Difficulty = h.Difficulty
	enc.Number = h.Number
	enc.GasLimit = h.GasLimit
	enc.GasUsed = h.GasUsed
	enc.Time = h.Time
	enc.Extra = h.Extra
	enc.MixDigest = h.MixDigest
	enc.Nonce = h.Nonce
	enc.BaseFee = h.BaseFee
	enc.Committee = h.Committee
	enc.ProposerSeal = h.ProposerSeal
	enc.Round = h.Round
	enc.CommittedSeals = h.CommittedSeals
	enc.LastEpochBlock = h.LastEpochBlock
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (h *Header) UnmarshalJSON(input []byte) error {
	type Header struct {
		ParentHash     *common.Hash    `json:"parentHash"       gencodec:"required"`
		UncleHash      *common.Hash    `json:"sha3Uncles"       gencodec:"required"`
		Coinbase       *common.Address `json:"miner"            gencodec:"required"`
		Root           *common.Hash    `json:"stateRoot"        gencodec:"required"`
		TxHash         *common.Hash    `json:"transactionsRoot" gencodec:"required"`
		ReceiptHash    *common.Hash    `json:"receiptsRoot"     gencodec:"required"`
		Bloom          *Bloom          `json:"logsBloom"        gencodec:"required"`
		Difficulty     *big.Int        `json:"difficulty"       gencodec:"required"`
		Number         *big.Int        `json:"number"           gencodec:"required"`
		GasLimit       *uint64         `json:"gasLimit"         gencodec:"required"`
		GasUsed        *uint64         `json:"gasUsed"          gencodec:"required"`
		Time           *uint64         `json:"timestamp"        gencodec:"required"`
		Extra          []byte          `json:"extraData"        gencodec:"required"`
		MixDigest      *common.Hash    `json:"mixHash"`
		Nonce          *BlockNonce     `json:"nonce"`
		BaseFee        *big.Int        `json:"baseFeePerGas"`
		Committee      *Committee      `json:"committee"`
		ProposerSeal   []byte          `json:"proposerSeal"        gencodec:"required"`
		Round          *uint64         `json:"round"               gencodec:"required"`
		CommittedSeals [][]byte        `json:"committedSeals"      gencodec:"required"`
		LastEpochBlock *big.Int        `json:"lastEpochBlock"      gencodec:"required"`
	}
	var dec Header
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ParentHash == nil {
		return errors.New("missing required field 'parentHash' for Header")
	}
	h.ParentHash = *dec.ParentHash
	if dec.UncleHash == nil {
		return errors.New("missing required field 'sha3Uncles' for Header")
	}
	h.UncleHash = *dec.UncleHash
	if dec.Coinbase == nil {
		return errors.New("missing required field 'miner' for Header")
	}
	h.Coinbase = *dec.Coinbase
	if dec.Root == nil {
		return errors.New("missing required field 'stateRoot' for Header")
	}
	h.Root = *dec.Root
	if dec.TxHash == nil {
		return errors.New("missing required field 'transactionsRoot' for Header")
	}
	h.TxHash = *dec.TxHash
	if dec.ReceiptHash == nil {
		return errors.New("missing required field 'receiptsRoot' for Header")
	}
	h.ReceiptHash = *dec.ReceiptHash
	if dec.Bloom == nil {
		return errors.New("missing required field 'logsBloom' for Header")
	}
	h.Bloom = *dec.Bloom
	if dec.Difficulty == nil {
		return errors.New("missing required field 'difficulty' for Header")
	}
	h.Difficulty = dec.Difficulty
	if dec.Number == nil {
		return errors.New("missing required field 'number' for Header")
	}
	h.Number = dec.Number
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gasLimit' for Header")
	}
	h.GasLimit = *dec.GasLimit
	if dec.GasUsed == nil {
		return errors.New("missing required field 'gasUsed' for Header")
	}
	h.GasUsed = *dec.GasUsed
	if dec.Time == nil {
		return errors.New("missing required field 'timestamp' for Header")
	}
	h.Time = *dec.Time
	if dec.Extra == nil {
		return errors.New("missing required field 'extraData' for Header")
	}
	h.Extra = dec.Extra
	if dec.MixDigest != nil {
		h.MixDigest = *dec.MixDigest
	}
	if dec.Nonce != nil {
		h.Nonce = *dec.Nonce
	}
	if dec.BaseFee != nil {
		h.BaseFee = dec.BaseFee
	}
	if dec.Committee != nil {
		h.Committee = dec.Committee
	}
	if dec.ProposerSeal == nil {
		return errors.New("missing required field 'proposerSeal' for Header")
	}
	h.ProposerSeal = dec.ProposerSeal
	if dec.Round == nil {
		return errors.New("missing required field 'round' for Header")
	}
	h.Round = *dec.Round
	if dec.CommittedSeals == nil {
		return errors.New("missing required field 'committedSeals' for Header")
	}
	h.CommittedSeals = dec.CommittedSeals
	if dec.LastEpochBlock == nil {
		return errors.New("missing required field 'lastEpochBlock' for Header")
	}
	h.LastEpochBlock = dec.LastEpochBlock
	return nil
}
