// Code generated by MockGen. DO NOT EDIT.
// Source: consensus/tendermint/core/interfaces/broadcaster.go

// Package interfaces is a generated GoMock package.
package interfaces

import (
	reflect "reflect"

	message "github.com/autonity/autonity/consensus/tendermint/core/message"
	gomock "go.uber.org/mock/gomock"
)

// MockBroadcaster is a mock of Broadcaster interface.
type MockBroadcaster struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcasterMockRecorder
}

// MockBroadcasterMockRecorder is the mock recorder for MockBroadcaster.
type MockBroadcasterMockRecorder struct {
	mock *MockBroadcaster
}

// NewMockBroadcaster creates a new mock instance.
func NewMockBroadcaster(ctrl *gomock.Controller) *MockBroadcaster {
	mock := &MockBroadcaster{ctrl: ctrl}
	mock.recorder = &MockBroadcasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcaster) EXPECT() *MockBroadcasterMockRecorder {
	return m.recorder
}

// SignAndBroadcast mocks base method.
func (m *MockBroadcaster) SignAndBroadcast(msg *message.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SignAndBroadcast", msg)
}

// SignAndBroadcast indicates an expected call of SignAndBroadcast.
func (mr *MockBroadcasterMockRecorder) SignAndBroadcast(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignAndBroadcast", reflect.TypeOf((*MockBroadcaster)(nil).SignAndBroadcast), msg)
}
