// Code generated by MockGen. DO NOT EDIT.
// Source: consensus/tendermint/committee/committee_interface.go

package committee

import (
	common "github.com/clearmatics/autonity/common"
	types "github.com/clearmatics/autonity/core/types"
	gomock "github.com/golang/mock/gomock"
	big "math/big"
	reflect "reflect"
)

// MockSet is a mock of Set interface
type MockSet struct {
	ctrl     *gomock.Controller
	recorder *MockSetMockRecorder
}

// MockSetMockRecorder is the mock recorder for MockSet
type MockSetMockRecorder struct {
	mock *MockSet
}

// NewMockSet creates a new mock instance
func NewMockSet(ctrl *gomock.Controller) *MockSet {
	mock := &MockSet{ctrl: ctrl}
	mock.recorder = &MockSetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockSet) EXPECT() *MockSetMockRecorder {
	return _m.recorder
}

// Size mocks base method
func (_m *MockSet) Size() int {
	ret := _m.ctrl.Call(_m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size
func (_mr *MockSetMockRecorder) Size() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Size", reflect.TypeOf((*MockSet)(nil).Size))
}

// Committee mocks base method
func (_m *MockSet) Committee() types.Committee {
	ret := _m.ctrl.Call(_m, "Committee")
	ret0, _ := ret[0].(types.Committee)
	return ret0
}

// Committee indicates an expected call of Committee
func (_mr *MockSetMockRecorder) Committee() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Committee", reflect.TypeOf((*MockSet)(nil).Committee))
}

// GetByIndex mocks base method
func (_m *MockSet) GetByIndex(i int) (types.CommitteeMember, error) {
	ret := _m.ctrl.Call(_m, "GetByIndex", i)
	ret0, _ := ret[0].(types.CommitteeMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIndex indicates an expected call of GetByIndex
func (_mr *MockSetMockRecorder) GetByIndex(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetByIndex", reflect.TypeOf((*MockSet)(nil).GetByIndex), arg0)
}

// GetByAddress mocks base method
func (_m *MockSet) GetByAddress(addr common.Address) (int, types.CommitteeMember, error) {
	ret := _m.ctrl.Call(_m, "GetByAddress", addr)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(types.CommitteeMember)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByAddress indicates an expected call of GetByAddress
func (_mr *MockSetMockRecorder) GetByAddress(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetByAddress", reflect.TypeOf((*MockSet)(nil).GetByAddress), arg0)
}

// GetProposer mocks base method
func (_m *MockSet) GetProposer(round int64, height *big.Int) types.CommitteeMember {
	ret := _m.ctrl.Call(_m, "GetProposer", round, height)
	ret0, _ := ret[0].(types.CommitteeMember)
	return ret0
}

// GetProposer indicates an expected call of GetProposer
func (_mr *MockSetMockRecorder) GetProposer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetProposer", reflect.TypeOf((*MockSet)(nil).GetProposer), arg0, arg1)
}

// IsProposer mocks base method
func (_m *MockSet) IsProposer(round int64, height *big.Int, address common.Address) bool {
	ret := _m.ctrl.Call(_m, "IsProposer", round, height, address)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProposer indicates an expected call of IsProposer
func (_mr *MockSetMockRecorder) IsProposer(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "IsProposer", reflect.TypeOf((*MockSet)(nil).IsProposer), arg0, arg1, arg2)
}

// Copy mocks base method
func (_m *MockSet) Copy() Set {
	ret := _m.ctrl.Call(_m, "Copy")
	ret0, _ := ret[0].(Set)
	return ret0
}

// Copy indicates an expected call of Copy
func (_mr *MockSetMockRecorder) Copy() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Copy", reflect.TypeOf((*MockSet)(nil).Copy))
}

// F mocks base method
func (_m *MockSet) F() uint64 {
	ret := _m.ctrl.Call(_m, "F")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// F indicates an expected call of F
func (_mr *MockSetMockRecorder) F() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "F", reflect.TypeOf((*MockSet)(nil).F))
}

// Quorum mocks base method
func (_m *MockSet) Quorum() uint64 {
	ret := _m.ctrl.Call(_m, "Quorum")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Quorum indicates an expected call of Quorum
func (_mr *MockSetMockRecorder) Quorum() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Quorum", reflect.TypeOf((*MockSet)(nil).Quorum))
}
