# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant config for running Autonity E2E tests

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder "..", "/autonity"

  config.vm.provider "virtualbox" do |vb|
    # Use the same specs that GitHub runners do
    # http://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners
    vb.memory = "7168"
    vb.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get -y install make docker.io python3 python3-venv python3-pip \
      golang-docker-credential-helpers

    if ! [[ -f /usr/local/go/bin/go ]]; then
      wget -q -P /tmp/ https://dl.google.com/go/go1.15.5.linux-amd64.tar.gz
      tar -C /usr/local -xzf /tmp/go1.15.5.linux-amd64.tar.gz
      echo 'PATH=${PATH}:/usr/local/go/bin' >> /home/vagrant/.bashrc
    fi

    pip3 install -r /autonity/docker_e2e_test/requirements_docker_test.txt
  SHELL
end
