// Code generated by MockGen. DO NOT EDIT.
// Source: consensus/tendermint/core/core_backend.go

package core

import (
	context "context"
	common "github.com/clearmatics/autonity/common"
	autonity "github.com/clearmatics/autonity/contracts/autonity"
	core "github.com/clearmatics/autonity/core"
	types "github.com/clearmatics/autonity/core/types"
	event "github.com/clearmatics/autonity/event"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockBackend is a mock of Backend interface
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
}

// MockBackendMockRecorder is the mock recorder for MockBackend
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return _m.recorder
}

// Address mocks base method
func (_m *MockBackend) Address() common.Address {
	ret := _m.ctrl.Call(_m, "Address")
	ret0, _ := ret[0].(common.Address)
	return ret0
}

// Address indicates an expected call of Address
func (_mr *MockBackendMockRecorder) Address() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Address", reflect.TypeOf((*MockBackend)(nil).Address))
}

// AddSeal mocks base method
func (_m *MockBackend) AddSeal(block *types.Block) (*types.Block, error) {
	ret := _m.ctrl.Call(_m, "AddSeal", block)
	ret0, _ := ret[0].(*types.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSeal indicates an expected call of AddSeal
func (_mr *MockBackendMockRecorder) AddSeal(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AddSeal", reflect.TypeOf((*MockBackend)(nil).AddSeal), arg0)
}

// AskSync mocks base method
func (_m *MockBackend) AskSync(header *types.Header) {
	_m.ctrl.Call(_m, "AskSync", header)
}

// AskSync indicates an expected call of AskSync
func (_mr *MockBackendMockRecorder) AskSync(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AskSync", reflect.TypeOf((*MockBackend)(nil).AskSync), arg0)
}

// Broadcast mocks base method
func (_m *MockBackend) Broadcast(ctx context.Context, committee types.Committee, payload []byte) error {
	ret := _m.ctrl.Call(_m, "Broadcast", ctx, committee, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Broadcast indicates an expected call of Broadcast
func (_mr *MockBackendMockRecorder) Broadcast(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Broadcast", reflect.TypeOf((*MockBackend)(nil).Broadcast), arg0, arg1, arg2)
}

// Commit mocks base method
func (_m *MockBackend) Commit(proposalBlock *types.Block, round int64, seals [][]byte) error {
	ret := _m.ctrl.Call(_m, "Commit", proposalBlock, round, seals)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit
func (_mr *MockBackendMockRecorder) Commit(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Commit", reflect.TypeOf((*MockBackend)(nil).Commit), arg0, arg1, arg2)
}

// GetContractABI mocks base method
func (_m *MockBackend) GetContractABI() string {
	ret := _m.ctrl.Call(_m, "GetContractABI")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetContractABI indicates an expected call of GetContractABI
func (_mr *MockBackendMockRecorder) GetContractABI() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetContractABI", reflect.TypeOf((*MockBackend)(nil).GetContractABI))
}

// Gossip mocks base method
func (_m *MockBackend) Gossip(ctx context.Context, committee types.Committee, payload []byte) {
	_m.ctrl.Call(_m, "Gossip", ctx, committee, payload)
}

// Gossip indicates an expected call of Gossip
func (_mr *MockBackendMockRecorder) Gossip(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Gossip", reflect.TypeOf((*MockBackend)(nil).Gossip), arg0, arg1, arg2)
}

// HandleUnhandledMsgs mocks base method
func (_m *MockBackend) HandleUnhandledMsgs(ctx context.Context) {
	_m.ctrl.Call(_m, "HandleUnhandledMsgs", ctx)
}

// HandleUnhandledMsgs indicates an expected call of HandleUnhandledMsgs
func (_mr *MockBackendMockRecorder) HandleUnhandledMsgs(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "HandleUnhandledMsgs", reflect.TypeOf((*MockBackend)(nil).HandleUnhandledMsgs), arg0)
}

// LastCommittedProposal mocks base method
func (_m *MockBackend) LastCommittedProposal() (*types.Block, common.Address) {
	ret := _m.ctrl.Call(_m, "LastCommittedProposal")
	ret0, _ := ret[0].(*types.Block)
	ret1, _ := ret[1].(common.Address)
	return ret0, ret1
}

// LastCommittedProposal indicates an expected call of LastCommittedProposal
func (_mr *MockBackendMockRecorder) LastCommittedProposal() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "LastCommittedProposal", reflect.TypeOf((*MockBackend)(nil).LastCommittedProposal))
}

// Post mocks base method
func (_m *MockBackend) Post(ev interface{}) {
	_m.ctrl.Call(_m, "Post", ev)
}

// Post indicates an expected call of Post
func (_mr *MockBackendMockRecorder) Post(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Post", reflect.TypeOf((*MockBackend)(nil).Post), arg0)
}

// SetProposedBlockHash mocks base method
func (_m *MockBackend) SetProposedBlockHash(hash common.Hash) {
	_m.ctrl.Call(_m, "SetProposedBlockHash", hash)
}

// SetProposedBlockHash indicates an expected call of SetProposedBlockHash
func (_mr *MockBackendMockRecorder) SetProposedBlockHash(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SetProposedBlockHash", reflect.TypeOf((*MockBackend)(nil).SetProposedBlockHash), arg0)
}

// Sign mocks base method
func (_m *MockBackend) Sign(_param0 []byte) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Sign", _param0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign
func (_mr *MockBackendMockRecorder) Sign(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Sign", reflect.TypeOf((*MockBackend)(nil).Sign), arg0)
}

// Subscribe mocks base method
func (_m *MockBackend) Subscribe(types ...interface{}) *event.TypeMuxSubscription {
	_s := []interface{}{}
	for _, _x := range types {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "Subscribe", _s...)
	ret0, _ := ret[0].(*event.TypeMuxSubscription)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (_mr *MockBackendMockRecorder) Subscribe(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Subscribe", reflect.TypeOf((*MockBackend)(nil).Subscribe), arg0...)
}

// SyncPeer mocks base method
func (_m *MockBackend) SyncPeer(address common.Address) {
	_m.ctrl.Call(_m, "SyncPeer", address)
}

// SyncPeer indicates an expected call of SyncPeer
func (_mr *MockBackendMockRecorder) SyncPeer(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SyncPeer", reflect.TypeOf((*MockBackend)(nil).SyncPeer), arg0)
}

// VerifyProposal mocks base method
func (_m *MockBackend) VerifyProposal(_param0 types.Block) (time.Duration, error) {
	ret := _m.ctrl.Call(_m, "VerifyProposal", _param0)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyProposal indicates an expected call of VerifyProposal
func (_mr *MockBackendMockRecorder) VerifyProposal(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "VerifyProposal", reflect.TypeOf((*MockBackend)(nil).VerifyProposal), arg0)
}

// WhiteList mocks base method
func (_m *MockBackend) WhiteList() []string {
	ret := _m.ctrl.Call(_m, "WhiteList")
	ret0, _ := ret[0].([]string)
	return ret0
}

// WhiteList indicates an expected call of WhiteList
func (_mr *MockBackendMockRecorder) WhiteList() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "WhiteList", reflect.TypeOf((*MockBackend)(nil).WhiteList))
}

// BlockChain mocks base method
func (_m *MockBackend) BlockChain() *core.BlockChain {
	ret := _m.ctrl.Call(_m, "BlockChain")
	ret0, _ := ret[0].(*core.BlockChain)
	return ret0
}

// BlockChain indicates an expected call of BlockChain
func (_mr *MockBackendMockRecorder) BlockChain() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "BlockChain", reflect.TypeOf((*MockBackend)(nil).BlockChain))
}

// SetBlockchain mocks base method
func (_m *MockBackend) SetBlockchain(bc *core.BlockChain) {
	_m.ctrl.Call(_m, "SetBlockchain", bc)
}

// SetBlockchain indicates an expected call of SetBlockchain
func (_mr *MockBackendMockRecorder) SetBlockchain(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SetBlockchain", reflect.TypeOf((*MockBackend)(nil).SetBlockchain), arg0)
}

// MockTendermint is a mock of Tendermint interface
type MockTendermint struct {
	ctrl     *gomock.Controller
	recorder *MockTendermintMockRecorder
}

// MockTendermintMockRecorder is the mock recorder for MockTendermint
type MockTendermintMockRecorder struct {
	mock *MockTendermint
}

// NewMockTendermint creates a new mock instance
func NewMockTendermint(ctrl *gomock.Controller) *MockTendermint {
	mock := &MockTendermint{ctrl: ctrl}
	mock.recorder = &MockTendermintMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockTendermint) EXPECT() *MockTendermintMockRecorder {
	return _m.recorder
}

// Start mocks base method
func (_m *MockTendermint) Start(ctx context.Context, contract *autonity.Contract) {
	_m.ctrl.Call(_m, "Start", ctx, contract)
}

// Start indicates an expected call of Start
func (_mr *MockTendermintMockRecorder) Start(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Start", reflect.TypeOf((*MockTendermint)(nil).Start), arg0, arg1)
}

// Stop mocks base method
func (_m *MockTendermint) Stop() {
	_m.ctrl.Call(_m, "Stop")
}

// Stop indicates an expected call of Stop
func (_mr *MockTendermintMockRecorder) Stop() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Stop", reflect.TypeOf((*MockTendermint)(nil).Stop))
}

// GetCurrentHeightMessages mocks base method
func (_m *MockTendermint) GetCurrentHeightMessages() []*Message {
	ret := _m.ctrl.Call(_m, "GetCurrentHeightMessages")
	ret0, _ := ret[0].([]*Message)
	return ret0
}

// GetCurrentHeightMessages indicates an expected call of GetCurrentHeightMessages
func (_mr *MockTendermintMockRecorder) GetCurrentHeightMessages() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetCurrentHeightMessages", reflect.TypeOf((*MockTendermint)(nil).GetCurrentHeightMessages))
}

// CoreState mocks base method
func (_m *MockTendermint) CoreState() types.TendermintState {
	ret := _m.ctrl.Call(_m, "CoreState")
	ret0, _ := ret[0].(types.TendermintState)
	return ret0
}

// CoreState indicates an expected call of CoreState
func (_mr *MockTendermintMockRecorder) CoreState() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CoreState", reflect.TypeOf((*MockTendermint)(nil).CoreState))
}
