name: Downstream Tooling (new release)

on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger autonity.py build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_CLEARMATICSROBOT_PAT }}
          repository: autonity/autonity.py
          event-type: new_autonity_release
          client-payload: >
            {
              "run_id": "${{ github.run_id }}",
              "sha": "${{ github.sha }}",
              "ref": "${{ github.ref }}"
            }
